<a href="https://colab.research.google.com/github/balashiva0011/Introduction-to-python-pandas/blob/main/Pandas_and_numpy_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy
NumPy (Numerical Python) is a library for numerical computing in Python. It provides support for arrays, matrices, and a large collection of mathematical functions to operate on these data structures.

In [ ]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Calculate the mean
mean = np.mean(arr)
print(f"Mean: {mean}")

# Matrix multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2)
print("Matrix multiplication result:\n", result)

Mean: 3.0
Matrix multiplication result:
 [[19 22]
 [43 50]]


Explanation of Matrix Multiplication
Given two matrices:

𝐴
=
(
1
2
3
4
)
A=(
1
3
​
  
2
4
​
 )

𝐵
=
(
5
6
7
8
)
B=(
5
7
​
  
6
8
​
 )
The product
𝐶
=
𝐴
⋅
𝐵
C=A⋅B is computed as follows:

𝐶
[
𝑖
,
𝑗
]
=
∑
𝑘
(
𝐴
[
𝑖
,
𝑘
]
⋅
𝐵
[
𝑘
,
𝑗
]
)
C[i,j]=
k
∑
​
 (A[i,k]⋅B[k,j])
For
𝐶
[
0
,
0
]
C[0,0]:

𝐶
[
0
,
0
]
=
(
1
⋅
5
)
+
(
2
⋅
7
)
=
5
+
14
=
19
C[0,0]=(1⋅5)+(2⋅7)=5+14=19
For
𝐶
[
0
,
1
]
C[0,1]:

𝐶
[
0
,
1
]
=
(
1
⋅
6
)
+
(
2
⋅
8
)
=
6
+
16
=
22
C[0,1]=(1⋅6)+(2⋅8)=6+16=22
For
𝐶
[
1
,
0
]
C[1,0]:

𝐶
[
1
,
0
]
=
(
3
⋅
5
)
+
(
4
⋅
7
)
=
15
+
28
=
43
C[1,0]=(3⋅5)+(4⋅7)=15+28=43
For
𝐶
[
1
,
1
]
C[1,1]:

𝐶
[
1
,
1
]
=
(
3
⋅
6
)
+
(
4
⋅
8
)
=
18
+
32
=
50
C[1,1]=(3⋅6)+(4⋅8)=18+32=50
So, the resulting matrix
𝐶
C is:

𝐶
=
(
19
22
43
50
)
C=(
19
43
​

  22
50
​
 )

These methods and principles make it straightforward to perform

Pandas
Pandas is a library for data manipulation and analysis, providing data structures like Series and DataFrames. It is built on top of NumPy and offers powerful tools for working with structured data.

Example 2: Using the @ Operator

In [ ]:
import numpy as np

# Define two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication
C = A @ B
print("Matrix C (using @ operator):\n", C)

Matrix C (using @ operator):
 [[19 22]
 [43 50]]


Example 3: Using np.matmul()


In [ ]:
import numpy as np

# Define two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication
C = np.matmul(A, B)
print("Matrix C (using np.matmul):\n", C)

Matrix C (using np.matmul):
 [[19 22]
 [43 50]]


In [ ]:
import pandas as pd

# Create a DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)

df

Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [ ]:
# Display basic statistics
print(df.describe())

# Filter rows where Age > 28
filtered_df = df[df['Age'] > 28]
print(filtered_df)



        Age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0
      Name  Age         City
1      Bob   30  Los Angeles
2  Charlie   35      Chicago


In [ ]:
# Group by 'City' and calculate the mean age
grouped = df.groupby('City')['Age'].mean()
print(grouped)

City
Chicago        35.0
Los Angeles    30.0
New York       25.0
Name: Age, dtype: float64


Combining Pandas and NumPy

In [ ]:
import pandas as pd
import numpy as np

# Create a DataFrame
df = pd.DataFrame({
    'A': [1, 2, 3, np.nan, 5],
    'B': [5, 6, np.nan, 8, 9]
})
df.isnull().sum()


A    1
B    1
dtype: int64

In [ ]:
df.mean()

A    2.75
B    7.00
dtype: float64

In [ ]:
# Fill missing values using the mean of the column
df.fillna(df.mean(), inplace=True)
df

A    B
0  1.00  5.0
1  2.00  6.0
2  3.00  7.0
3  2.75  8.0
4  5.00  9.0